pipeline {
    agent { 
        any
    } 
    stages {
        stage('Checkout Git and Check Difference') {
            steps {
                checkout scm
            }
        // stage('Docker Build') {
        //     steps {
        //         checkout scm
        //     }
         }
    }
}